let moviesCount: any = 10; //O TIPO ANY BASICAMENTE DESATIVA O TIPO DAS SUAS VARIAVEIS

moviesCount = true //AQUI O CÓDIGO FUNCIONA POR QUE EU COLOQUEI ANY QUE TIRA A IMPORTANCIA DA TIPAGEM PARA A VARIÁVEL


