let nome: string = "Ulisses"; // ESSE É UM TIPO DE TIPAGEM EXPLICITA NO QUAL EU DIGO O QUE MINHHA VARIÁVEL É
//nome = 123  //SE EU MUDO O TIPO DA MINHA VARIÁVEL O TYPESCRIPT ACUSA UM ERRO

let idade = 123; //ESTE É UM TIPO DE INFERÊNCIA DE TIPAGEM AONDE OMITO O TIPO DA MINHA VARIÁVEL, MAS AO DECLARAR O VALOR ELE AUTOMATICAMENTE DEFINE COMO O TIPO QUE ESTÁ LÁ NA ATRIBUIÇÃO
// idade = "Ulisses"  // SE EU MUDO DA MESMA FORMA O TYPESCRIPT ACUSA O ERRO DE MUDANÇA DE TIPO

